### ISSUE TITLE
Format 問題  & tablename的命名規則

### ISSUE THREAD

**Issue by bloodnighttw** [TOPIC114/backend#15]
剛剛發現format有點不太好
再來是tablename有大寫開頭也有小寫開頭

我等等會放qodana分析工具來使用
另外在提交前請盡量讓pycharm內的警告降低

**Comment by bloodnighttw** [comment]
![image](https://github.com/TOPIC114/backend/assets/44264182/90074634-7e0c-49d3-b9fe-38de9dd7bd1a)

**Comment by bloodnighttw** [comment]
可以按下alt+enter來看怎樣改

**Comment by bloodnighttw** [comment]
另外table name我是傾向全小寫 空格用_分隔
不知道 @dddd123fff  你怎樣想

**Comment by bloodnighttw** [comment]
喔對 規範為PEP8

**Comment by dddd123fff** [comment]
OK

**Comment by bloodnighttw** [comment]
> 所以我要去修改嗎?

我之後會在發PR改

**Comment by bloodnighttw** [comment]
剩下大小寫的差別
