### ISSUE TITLE
與word表格不同

### ISSUE THREAD

**Issue by bloodnighttw** [TOPIC114/backend#18]
雖然是我沒review好code
反正就完全是兩個樣子
<img width="893" alt="截圖 2024-03-21 22 44 53" src="https://github.com/TOPIC114/backend/assets/44264182/653ec370-b258-4737-8eb2-44e0e273705a">
<img width="789" alt="截圖 2024-03-21 22 45 54" src="https://github.com/TOPIC114/backend/assets/44264182/2d7e27e3-7fbf-4415-aac9-ee0e3b89b48b">

有許多項目缺少 （這個有精簡過了）

寫完這個model記得去word上用黃色螢光筆標記
標示已做

**Comment by bloodnighttw** [comment]
還有先別做 這個東西還需要討論

**Comment by dddd123fff** [comment]
table先別做?

**Comment by bloodnighttw** [comment]
目前正在把討論過的資料庫表格重新整理過用到程式中 所以關閉
