### ISSUE TITLE
程式碼檢查工具無法檢查

### ISSUE THREAD

**Issue by bloodnighttw** [TOPIC114/backend#20]
如題
我發現PR如果是外部的 （自己fork出去的）
就會無法使用檢查工具

那解決辦法就是以後我們的分支都在此repo開
這邊順便說一下 需要做的設定

**Comment by bloodnighttw** [comment]
首先按兩下``shift``
搜尋 ``manage remote`` 並按下 ``enter``
你會看到這東西
改成跟圖片一樣就好
![image](https://github.com/TOPIC114/backend/assets/44264182/b908a5fd-f7ed-4ab5-81fc-b9cbfc749d1f)

**Comment by bloodnighttw** [comment]
那開分支的方法也是跟以前一樣
另外main我有設定保護
但還是盡量不要動它

**Comment by bloodnighttw** [comment]
先等等 看起來有點小狀況

**Comment by bloodnighttw** [comment]
找到解決辦法了
你先在github 創分支
![image](https://github.com/TOPIC114/backend/assets/44264182/4b1fcf3b-ce71-4d57-a053-c487b9156206)
創一個新的分支
![image](https://github.com/TOPIC114/backend/assets/44264182/6e341329-1463-4c9d-aead-ef6193d64a2b)

然後在pycharm選擇這個新的remote分支
![image](https://github.com/TOPIC114/backend/assets/44264182/b4b84e5f-0a98-4a13-b16e-db972336ff73)

**Comment by bloodnighttw** [comment]
@dddd123fff  你設定如果有問題在這邊說
沒問題也跟我講一下

**Comment by bloodnighttw** [comment]
結果一樣不行

**Comment by dddd123fff** [comment]
在自己的repo創分支嗎
我在這個repo創分支，在remote看不到

**Comment by dddd123fff** [comment]
我在自己的repo創的看的到，沒事了

**Comment by bloodnighttw** [comment]
額解決了

**Comment by bloodnighttw** [comment]
對 所以要修改remote origin

**Comment by bloodnighttw** [comment]
看起來是我可以上傳了

**Comment by bloodnighttw** [comment]
@dddd123fff 具體作法請參考
https://github.com/TOPIC114/backend/issues/20#issuecomment-2016434678
其他的不用改

**Comment by dddd123fff** [comment]
![螢幕擷取畫面 2024-03-23 211649](https://github.com/TOPIC114/backend/assets/148472706/7479f366-4a3a-42c6-bf9d-bc0583eb927e)

**Comment by dddd123fff** [comment]
之後程式就在remote的分支寫，然後發PR的方式不變這樣?

**Comment by bloodnighttw** [comment]
YES
